---
fail2ban_loglevel: 3
fail2ban_logtarget: /var/log/fail2ban.log
fail2ban_socket: /var/run/fail2ban/fail2ban.sock

fail2ban_ignoreip: 127.0.0.1/8
fail2ban_bantime: 600
fail2ban_maxretry: 6

fail2ban_backend: polling

fail2ban_destemail: root@localhost
fail2ban_banaction: iptables-multiport
fail2ban_mta: sendmail
fail2ban_protocol: tcp
fail2ban_chain: INPUT

fail2ban_action: action_

fail2ban_services:
  - name: ssh
    port: ssh
    filter: sshd
    logpath: /var/log/auth.log

ntp_pkg_state: 'installed'
ntp_service_state: 'started'
ntp_service_enabled: 'yes'

ntp_config_server: [ 'time.nist.gov', '1.pool.ntp.org' ]
ntp_config_restrict:
- '-4 default kod notrap nomodify nopeer noquery'
- '-6 default kod notrap nomodify nopeer noquery'
- '127.0.0.1'
- '::1'

ntp_config_listen: []

ntp_config_filegen:
- 'loopstats file loopstats type day enable'
- 'peerstats file peerstats type day enable'
- 'clockstats file clockstats type day enable'

ntp_config_statistics: 'loopstats peerstats clockstats'
ntp_config_crypto: ''
ntp_config_includefile: ''
ntp_config_keys: ''
ntp_config_trustedkey: ''
ntp_config_requestkey: ''
ntp_config_controlkey: ''
ntp_config_broadcast: ''
ntp_config_broadcastclient: ''
ntp_config_multicastclient: ''
ntp_config_tinker_panic_enabled: ''

ntp_config_driftfile: /var/lib/ntp/ntp.drift