---

- name: Certificate are installed
  stat:
    path: "/etc/letsencrypt/live/{{ pythondev_domain }}"
  register: pythondev_certificate

- name: Stop nginx
  service:
    name: nginx.service
    state: stopped
  when: pythondev_certificate.stat.isdir is not defined and systemd_enabled == true

- name: Generate certificate
  command: "/usr/bin/certbot certonly --standalone -d {{ pythondev_domain }} -m {{ email }} -n --agree-tos {{letsencrypt_args}}"
  when: pythondev_certificate.stat.isdir is not defined and letsencrypt_enabled == true

- name: Start nginx
  service:
    name: nginx.service
    state: started
  when: pythondev_certificate.stat.isdir is not defined and systemd_enabled == true
