---
ansible_ssh_host: 45.55.169.185
ansible_ssh_port: 22
ansible_ssh_user: root
email: pythondev.slack@gmail.com
sirbot_domain: sirbot.pyslackers.com
pythondev_domain: pyslackers.com
letsencrypt_run: true
systemd_enabled: true
travis_ci: false
