---
- name: Install fail2ban
  apt:
    pkg: fail2ban
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"
  notify:
    - restart fail2ban

- name: Configure fail2ban
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
  with_items:
    - etc/fail2ban/jail.local
    - etc/fail2ban/fail2ban.local
  notify:
    - restart fail2ban

- name: Ensure auth.log exists
  file:
    path: /var/log/auth.log
    state: touch

- name: Start fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
  when: systemd_enabled == true
