---
- include: common.yml
  tags:
    - server-setup
    - common

- include: fail2ban.yml
  tags:
    - server-setup
    - fail2ban

- include: ntp.yml
  tags:
    - server-setup
    - ntp

- include: sysstat.yml
  tags:
    - server-setup
    - sysstat