---

- name: Certificate are installed
  stat:
    path: "/etc/letsencrypt/live/{{ sirbot_domain }}"
  register: sirbot_certificate

- name: Stop nginx
  service:
    name: nginx.service
    state: stopped
  when: sirbot_certificate.stat.isdir is not defined

- name: Generate certificate
  command: "/usr/bin/certbot certonly --standalone -d {{ sirbot_domain }} -m {{ email }} -n --agree-tos"
  when: sirbot_certificate.stat.isdir is not defined and letsencrypt_run == true

- name: Start nginx
  service:
    name: nginx.service
    state: started
  when: sirbot_certificate.stat.isdir is not defined
